# Generated by Django 5.1.6 on 2025-02-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.CharField(max_length=50, verbose_name='Номер комнаты')),
                ('seat_number', models.CharField(max_length=40, verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='ФИО')),
                ('nationality', models.CharField(max_length=50, verbose_name='Регистрация')),
                ('organization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Организация')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заселения')),
                ('summ', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('check_out_date', models.DateTimeField(verbose_name='Дата выселения')),
                ('payment_method', models.CharField(choices=[('КР', 'Карта'), ('НЛ', 'Наличные'), ('БН', 'Безнал')], max_length=3, verbose_name='Способ оплаты')),
                ('room_occupied', models.BooleanField(default=False, verbose_name='Комната занята')),
                ('number_phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменений')),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Основная таблица',
                'verbose_name_plural': 'Основные таблицы',
            },
        ),
    ]
