# Generated by Django 5.1.6 on 2025-02-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='room_occupied',
        ),
        migrations.AddField(
            model_name='maintable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room', verbose_name='Комната'),
        ),
        migrations.AddField(
            model_name='maintable',
            name='seat_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер места'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number_room', 'seat_number')},
        ),
    ]
