# Generated by Django 5.1.6 on 2025-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_maintable_room_occupied_maintable_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Занята'),
        ),
    ]
