# Generated by Django 5.1.6 on 2025-02-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='seat_number',
        ),
    ]
