# Generated by Django 5.1.6 on 2025-02-25 11:09

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_maintable_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintable',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='number_phone',
            field=models.CharField(max_length=50, validators=[main.validators.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
