# Generated by Django 5.1.6 on 2025-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_maintable_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/', verbose_name='Фото паспорта'),
        ),
    ]
