# Generated by Django 5.1.6 on 2025-02-25 12:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_maintable_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.MainTable.user_photo_path, verbose_name='Фото паспорта'),
        ),
        migrations.AlterField(
            model_name='room',
            name='seat_number',
            field=models.CharField(default='доп', max_length=40, verbose_name='Номер места'),
        ),
    ]
